name: zyq.mybluemix.net Awake

on:
  schedule:
    - cron: "*/60 * * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://zyq.mybluemix.net/"
